---
  headless: True
  simulation:
    active: True
    live: False
    image_paths:
      camera_view: 'computer_vision/simulation/images/photo_1.jpg'
      arrow: 'computer_vision/simulation/images/arrow.jpg'
  network:
    host: !!str '10.0.11.116'
    port: !!int 2004
    port_cam0: !!int 2005
    stream_en_cam0: !!bool True
    port_cam1: !!int 2006
    stream_en_cam1: !!bool False
  car_comm_interface: !!str "serial"   # "serial", "can", "pwm"
  serial:
    active: !!bool false
    port: !!int 0
  can:
    active: !!bool false
    interface: !!str "socketcan"
    channel: !!str "can0"
  camera0:
    id: !!int 0
    size:
      px: !!int 76
      mm: !!int 52
      distance: !!int 500
  qr_code_size:
    px: !!int 191
    mm: !!int 79
    distance: !!int 515
  a_star:
    weight: !!int 4
    penalty: !!int 2
  environment:
    size: !!seq [50, 50]
    real_size: !!int 50
  object_id:
    end_point: !!int 2
    car: !!int 10
    QR: !!int 20
  camera:
    active: !!str 'web'
    camera_resolution:
      web: !!seq [1280, 800]
      logi: !!seq [1920, 1080]
  spline:
    tension: !!int 0
    velocity: !!float 100.0
...
