---
qr_code_size:
  px: !!int 76
  mm: !!int 52
  distance: !!int 500
sign_size:
  px: !!int 10
  mm: !!int 61
  distance: !!int 200
lane_detector:
  canny: !!seq [50, 150]
  blur: !!int 5
  hough: !!seq [100, 250]
parking_slot_detector:
  hough: !!seq [200, 5]
  iterations: !!seq [5, 2]
environment:
  sizex: !!int 10
  sizey: !!int 11
gui:
  window_width: !!int 600
...
