name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.1.12-0
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: cache deps
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}
      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'
      - run: poetry run pytest
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cache poetry install
        uses: actions/cache@v3
        with:
          path: ~/.local
          key: poetry-1.1.12-0
      - uses: snok/install-poetry@v1
        with:
          version: 1.2.2
          virtualenvs-create: false
          virtualenvs-in-project: false
      - run: |
          poetry install --no-interaction --no-root
      - name: Python Code Quality and Lint
        uses: ricardochaves/python-lint@v1.3.0
        with:
          python-root-list: "computer_vision"
          use-pylint: true
          use-pycodestyle: true
          use-flake8: false
          use-black: false
          use-mypy: true
          use-isort: false
          # extra-pylint-options: ""
          # extra-pycodestyle-options: ""
          # extra-flake8-options: ""
          # extra-black-options: ""
          # extra-mypy-options: ""
          # extra-isort-options: ""

      # - name: Set up Python 3.10
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: 3.10
      #   run:
